---
# roles/vagrant/tasks/debug-playbook-vars.yml

# Debug other values or specific values you want printed last


- name: "Debug - ansible playbook variable values"
  debug: msg="{{ vars }}"
  when: vagrant_debug


- name: "Debug value of playbook vars"
  debug: msg="{{ vars | to_yaml }}"
  when: vagrant_debug
